import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author markoc
 */
public class CustomJList extends javax.swing.JPanel {
    Meal selectedMeal;
    DefaultListModel listModel;
    int listSelectedIndex = -1;
    /**
     * Creates new form CustomJList
     */
    public CustomJList(String dayName, String date, CustomListModel listModel, ArrayList<Integer> listOfDisabledCells, Meal selectedMeal, boolean isPrinted) {
        initComponents();
        this.listModel = listModel;
        this.selectedMeal = selectedMeal;
        this.dayName.setText(dayName);
        this.date.setText(date);
        this.listSelectedIndex = (selectedMeal.getMealNumber() > -1) ? selectedMeal.getMealNumber()-1 : -1;
        
        customJList.setModel(listModel);
        customJList.setCellRenderer(new MealListItemRenderer(isPrinted, listSelectedIndex));
        customJList.setSelectionModel(new DefaultListSelectionModel(){
            @Override
            public void setSelectionInterval(int index0, int index1) {
                if (index0==index1) {
                    if (isSelectedIndex(index0) || listOfDisabledCells.contains(index0)) {
                        removeSelectionInterval(index0, index0);
                        return;
                    }
                }
                
                if(isPrinted)
                    super.setSelectionInterval(listSelectedIndex, listSelectedIndex);
                else
                    super.setSelectionInterval(index0, index0);
            }

            @Override
            public void addSelectionInterval(int index0, int index1) {
                // do nothing
            }
        });
        
        customJList.setSelectedIndex(listSelectedIndex);
    }
    
    public int getSelectedIndex()
    {
        return customJList.getSelectedIndex();
    }
    
    public String getDate()
    {
        return date.getText();
    }
    
    public boolean hasPreviousOrderEntry()
    {
        return selectedMeal.getId() != -1;
    }
    
    public int getOldMealID()
    {
        return selectedMeal.getId();
    }
    
    public int getNewMealID()
    {
        if(customJList.getSelectedIndex() == -1)
            return -1;
        
        Meal newMeal = (Meal) listModel.getElementAt(customJList.getSelectedIndex());
        return newMeal.getId();
    }
    
    public boolean hasChanged()
    {
        int selectedMealNumber = (selectedMeal.getMealNumber() == -1) ? -1: selectedMeal.getMealNumber()-1;
        return customJList.getSelectedIndex() != selectedMealNumber;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customJList = new javax.swing.JList<>();
        dayName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        customJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        dayName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dayName.setText("jLabel1");

        date.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        date.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dayName)
                    .addComponent(date)
                    .addComponent(customJList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date)
                .addGap(7, 7, 7)
                .addComponent(customJList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> customJList;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dayName;
    // End of variables declaration//GEN-END:variables
}
