
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author markoc
 */
public class EditUserPane extends javax.swing.JPanel {


    /**
     * Creates new form EditUserPane
     */
    public EditUserPane() {
        initComponents();
    }

    /**
     * GUI panel to edit the user.
     * 
     * @param userId 
     *        self-explanatory
     * @param firstName 
     *        self-explanatory
     * @param lastName 
     *        self-explanatory
     * @param superUser
     *        Recognizes users role. Parameter {@code true} gives the user administration rights
     * @param superUserCheckBoxEnabled 
     *        This should be set to {@code false} when the user is editing himself
     */
    public EditUserPane(int userId, String firstName, String lastName, boolean superUser, boolean superUserCheckBoxEnabled)
    {
        this();
        textFieldUserId.setText(String.valueOf(userId));
        textFieldFirstName.setText(firstName);
        textFieldLastName.setText(lastName);
        checkBoxSuperUser.setSelected(superUser);
        checkBoxSuperUser.setEnabled(superUserCheckBoxEnabled);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableId = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelSuperUser = new javax.swing.JLabel();
        checkBoxSuperUser = new javax.swing.JCheckBox();
        textFieldUserId = new javax.swing.JTextField();
        textFieldFirstName = new javax.swing.JTextField();
        textFieldLastName = new javax.swing.JTextField();

        lableId.setText("ID");

        labelFirstName.setText("First Name");

        labelLastName.setText("Last Name");

        labelSuperUser.setText("Super User");

        checkBoxSuperUser.setText(" ");
        checkBoxSuperUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSuperUserActionPerformed(evt);
            }
        });

        textFieldUserId.setEditable(false);
        textFieldUserId.setText("-1");
        textFieldUserId.setEnabled(false);

        textFieldFirstName.setText("null");

        textFieldLastName.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFirstName)
                    .addComponent(labelLastName)
                    .addComponent(labelSuperUser)
                    .addComponent(lableId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkBoxSuperUser)
                    .addComponent(textFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(textFieldLastName))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableId)
                    .addComponent(textFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName)
                    .addComponent(textFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuperUser)
                    .addComponent(checkBoxSuperUser)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxSuperUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSuperUserActionPerformed
        String superUserActionWord = (getSuperUser()) ? "add" : "remove";
        
        int option = JOptionPane.showOptionDialog(this, "Are you sure you want to "+superUserActionWord+" super user rights?", 
                "Super User Rights Change",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE, null, null, null);
        
        if(option == 1) // NO
            // reset checkbox
            checkBoxSuperUser.setSelected(!getSuperUser());
        
    }//GEN-LAST:event_checkBoxSuperUserActionPerformed

    public String getFirstName()
    {
        return textFieldFirstName.getText();
    }
    
    public String getLastName()
    {
        return textFieldLastName.getText();
    }
    
    public boolean getSuperUser()
    {
        return checkBoxSuperUser.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxSuperUser;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelSuperUser;
    private javax.swing.JLabel lableId;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldLastName;
    private javax.swing.JTextField textFieldUserId;
    // End of variables declaration//GEN-END:variables
}
